### ISSUE TITLE
Created By should be the original creator not the person who accepted the WIT

### ISSUE THREAD

**Issue by chataylor** [mohitbagra/vsts-extensions-bugbash-pro#15]
When "accepting" a reported bug in the extension, the newly created WIT assigns the "Created By" field to the person who accepted the bug. This is confusing as there is no association with the person who originally identified the bug.

**Comment by mohitbagra** [comment]
There is no way to impersonate another user in REST api, unless we have the PAT for that user. So we cannot set CreatedBy field of a workitem manually as its set automatically from server based on request context.
However, I made a change that the accepted item will now show a comment like this -

![image](https://user-images.githubusercontent.com/3766956/27546363-91424fe8-5a60-11e7-8581-9ceb4dcaa783.png)

This should be good enough

**Comment by chataylor** [comment]
Nice! Thanks for the fix, Mohit.
