### ISSUE TITLE
Let the user choose a tag to add to all accepted work items

### ISSUE THREAD

**Issue by defu** [mohitbagra/vsts-extensions-bugbash-pro#41]
This would be a lighter weight form other existing template functionality, which I think is a HUGE value add. Just a text input box on bug bash config that will be added as a tag on all work items created. This will make it super easy to find items after the bug bash is completed.

**Comment by mohitbagra** [comment]
This will fall under https://github.com/mohitbagra/vsts-extensions/issues/9
