### ISSUE TITLE
404 Errors with on-premise TFS 2017 Update 2

### ISSUE THREAD

**Issue by sumo300** [mohitbagra/vsts-extensions-bugbash-pro#60]
The 2 following URLs are coming up as 404 errors:

https://[tfsCollectionUrl]/_apis/ExtensionManagement/InstalledExtensions/mohitbagra/bugbashpro/Data/Scopes/Default/Current/Collections/bugbashes/Documents

https://[tfsCollectionUrl]/_apis/ExtensionManagement/InstalledExtensions/mohitbagra/bugbashpro/Data/Scopes/Default/Current/Collections/UserSettings_543e59bc-2c8d-4ba7-b5e2-8882bb030c29/Documents

**Comment by mohitbagra** [comment]
This is expected. This web call throws a 404 if the desired data/setting doesnt exist in extension blob. It shouldnt affect the extension's functionality.

For eg - To get a list of all bug bashes, this call is made. But if no bug bashes have been created yet, this call throws a 404 and the extension handles that accordingly
