### ISSUE TITLE
Unable to link to bug bash items - only entire results view

### ISSUE THREAD

**Issue by ostreifel** [mohitbagra/vsts-extensions-bugbash-pro#70]

**Comment by mohitbagra** [comment]
This feature would arrive in next update (probably this week). I added a double click handler on each bug bash item row - which will open the item editor in a maximized view and add an ?itemid param to the url.
You can then share that url to open a particular bug bash item.
It works much like our own triage view (except the up/down navigator buttons in maximized view of item editor)
